project:
  type: website
  output-dir: docs

website:
  title: "Roberto Ezcurra" 
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: contact.qmd
        text: Contact   
        
    
      
        
        

format:
  html:
    theme: united

editor: visual

