---
title: "Research"
---

<br>



[Kin-based institutions and state capacity](https://doi.org/10.1016/j.ejpoleco.2025.102676), European Journal of Political Economy 88, 102676, 2025.

[Irrigation agriculture and income redistribution](https://doi.org/10.1007/s10888-025-09672-x), Journal of Economic Inequality, 2025.

[Kin networks and quality of government: a regional analysis](https://doi.org/10.1007/s00168-024-01324-8), Annals of Regional Science 73 (4), pp. 2117-2142, 2024.

[Sunlight, culture and state capacity](https://doi.org/10.1111/kykl.12367), Kyklos 77 (2), pp. 285-315, 2024. 

[Political equality and quality of government](https://onlinelibrary.wiley.com/doi/full/10.1111/kykl.12295), Kyklos 75 (2), pp. 269-293, 2022. (With [Izaskun Zuazu](https://sites.google.com/site/izaskunzuazu/home).)

[Individualism and political instability](https://www.sciencedirect.com/science/article/pii/S0176268020301075), European Journal of Political Economy 66, 101959, 2021.

[Globalization and spatial inequality: Does economic integration affect regional disparities?](https://link.springer.com/article/10.1007/s00168-021-01050-5), Annals of Regional Science 67 (2), pp. 335-358, 2021. (With [Alba Del Villar](https://albadelvillar.wordpress.com/).) 

[Do wealth levels affect the contribution to negative externalities?](https://www.sciencedirect.com/science/article/abs/pii/S2214804319304549), Journal of Behavioral and Experimental Economics 87, 101579, 2020. (With Juan Miguel Benito-Ostolaza and Nuria Osés-Eraso.)

[Quality of government in European regions: Do spatial spillovers matter?](https://doi.org/10.1080/00343404.2019.1665644), Regional Studies 54 (8), pp. 1032-1042, 2020. (With Vicente Rios.)

[Interregional inequality and civil conflict: Are spatial disparities a threat to stability and peace?](https://doi.org/10.1080/10242694.2018.1446621), Defence and Peace Economics 30 (7), pp. 759-782, 2019.

[Regional disparities and within-country inequality in the European Union](http://www.uhu.es/publicaciones/ojs/index.php/REM/article/view/3907), Revista de Economía Mundial 51, pp. 139-162, 2019.

[Quality of government and regional resilience in the European Union. Evidence from the Great Recession](https://doi.org/10.1111/pirs.12417), Papers in Regional Science 98 (3), 1267-1290, 2019. (With Vicente Rios.)

[Group concentration and violence: Does ethnic segregation affect domestic terrorism?](https://doi.org/10.1080/10242694.2017.1315710), Defence and Peace Economics 30 (1), pp. 46-71, 2019.

[Does ethnic segregation matter for spatial inequality?](https://www.academic.oup.com/joeg/article-abstract/17/6/1149/3760071?redirectedFrom=fulltext), Journal of Economic Geography 17 (6), pp. 1149–1178, 2017. (With [Andrés Rodríguez-Pose](http://personal.lse.ac.uk/RODRIGU1/).) Related [Vox](http://voxeu.org/article/ethnic-segregation-and-spatial-income-inequality) column.

[Is government decentralization useful in the fight against domestic terrorism? A cross-country analysis](http://journals.sagepub.com/doi/abs/10.1177/0263774x16665363), Environment and Planning C: Politics and Space 35 (5), pp. 872-897, 2017.

[Is there a link between globalisation and civil conflict?](http://onlinelibrary.wiley.com/doi/10.1111/twec.12514/full), The World Economy 40 (12), pp. 2592-2610, 2017. (With Beatriz Manotas.)

[Terrorism and spatial disparities: Does interregional inequality matter?](http://www.sciencedirect.com/science/article/pii/S0176268016000057), European Journal of Political Economy 42, pp. 60-74, 2016. (With David Palacios.)

[Volatility and regional growth in Europe. Does space matter?](http://www.tandfonline.com/doi/abs/10.1080/17421772.2015.1062123?journalCode=rsea20) Spatial Economic Analysis 10 (3), pp. 344-368, 2015. (With Vicente Rios.)

[Fiscal decentralization and internal conflict: An empirical investigation](http://epc.sagepub.com/content/33/3/580.abstract), Environment and Planning C: Government and Policy 33 (3), pp. 580-600, 2015.

[Negative externalities in cropping decisions: Private versus common land](http://www.sciencedirect.com/science/article/pii/S0921800914001864), Ecological Economics  105, pp. 185-192, 2014. (With [Juan Miguel Benito](http://www.econ.unavarra.es/~jbenito/index.html) and Nuria Osés.)

[Government quality and spatial inequality: A cross-country analysis](http://epn.sagepub.com/content/46/7/1732.abstract?id=a130046p), Environment and Planning A, 46 (7), pp. 1732-1753, 2014. (With [Andrés Rodríguez-Pose](http://personal.lse.ac.uk/RODRIGU1/).) Related [Vox](http://voxeu.org/article/government-and-spatial-inequality) column.

[Trade openness and spatial inequality in emerging countries](http://www.tandfonline.com/doi/pdf/10.1080/17421772.2014.891155), Spatial Economic Analysis 9 (2), pp. 162-182, 2014. (With [Andrés Rodríguez-Pose](http://personal.lse.ac.uk/RODRIGU1/).)

[Polarization trends across the European regions](http://region-developpement.univ-tln.fr/fr/pdf/R38/2_Ezcurra.pdf), Région et Développement 38, pp. 2-18, 2014.

[Political decentralization, economic growth and regional disparities in the OECD](http://www.tandfonline.com/doi/pdf/10.1080/00343404.2012.731046), Regional Studies 47 (3), pp. 388-401, 2013. (With [Andrés Rodríguez-Pose](http://personal.lse.ac.uk/RODRIGU1/).)

[Does economic globalization affect regional inequality? A cross-country analysis](http://www.sciencedirect.com/science/article/pii/S0305750X13001642), World Development 52, pp. 92-103, 2013. (With [Andrés Rodríguez-Pose](http://personal.lse.ac.uk/RODRIGU1/).)

[Is there cross-country convergence in government quality? A non-parametric analysis](http://www.accessecon.com/Pubs/EB/2013/Volume33/EB-13-V33-I4-P250.pdf), Economics Bulletin 33 (4), pp. 2661-2671, 2013. (With Vicente Rios.)

[Is there a link between globalization and governance?](http://epc.sagepub.com/content/30/5/848.short) Environment and Planning C: Government and Policy 30 (5), pp. 848-870, 2012.

[Is fiscal decentralization harmful for economic growth? Evidence from OECD countries](http://joeg.oxfordjournals.org/content/11/4/619), Journal of Economic Geography 11 (4), pp. 619-643, 2011. (With [Andrés Rodríguez-Pose](http://personal.lse.ac.uk/RODRIGU1/).)

[Decentralization of social protection expenditure and economic growth in the OECD](http://publius.oxfordjournals.org/content/41/1/146), Publius: The Journal of Federalism 41 (1), pp. 146-157, 2011. (With [Andrés Rodríguez-Pose](http://personal.lse.ac.uk/RODRIGU1/).)

[Unemployment volatility and regional specialization in the European Union](http://www.tandfonline.com/doi/abs/10.1080/00343401003713332), Regional Studies 45 (8), pp. 1121-1137, 2011.

[Agricultural productivity in the European regions: Trends and explanatory factors](http://eur.sagepub.com/content/early/2010/11/24/0969776410381037), European Urban and Regional Studies 18 (2), pp. 113-135, 2011. (With Belén Iráizoz, Pedro Pascual and Manuel Rapún.)

[Education and gender bias in the sex ratio at birth: Evidence from India](http://link.springer.com/article/10.1353%2Fdem.0.0089), Demography 47 (1), pp. 249-268, 2010. (With [Rebeca Echávarri](http://www.econ.unavarra.es/%7Erebeca/index.html).)

[Does decentralization matter for regional disparities? A cross-country analysis](http://joeg.oxfordjournals.org/content/10/5/619), Journal of Economic Geography 10 (5), pp. 619-644, 2010. (With [Andrés Rodríguez-Pose](http://personal.lse.ac.uk/RODRIGU1/).)

[Sectoral volatility and regional growth in the European Union](http://epc.sagepub.com/content/28/2/369.abstract?id=c09186), Environment and Planning C: Government and Policy 28 (2), pp. 369-380, 2010.

[Does income polarization affect economic growth? The case of the European regions](http://www.tandfonline.com/doi/abs/10.1080/00343400701808899), Regional Studies 43 (2), pp. 267-285, 2009.

[Spatial effects in website adoption by firms in European regions](http://onlinelibrary.wiley.com/doi/10.1111/j.1468-2257.2008.00461.x/abstract), Growth and Change 40 (1), pp. 54-84, 2009. (With Margarita Billón and Fernando Lera.)

[Cross-country disparities in health care expenditure: A factor decomposition](http://onlinelibrary.wiley.com/doi/10.1002/hec.1374/abstract), Health Economics 18 (4), pp. 479-485, 2009. (With [Jorge Alcalde-Unzu](https://sites.google.com/site/alcaldeunzu/) and Pedro Pascual.)

[Polarization trends across the US states](http://www.tandfonline.com/doi/abs/10.1080/13504850701222194?journalCode=rael20),  Applied Economics Letters 16 (9), pp. 897-902, 2009.

[Total factor productivity, efficiency and technological change in the European regions: A non-parametric approach](http://epn.sagepub.com/content/41/5/1152.abstract?id=a40362), Environment and Planning A 41 (5), pp. 112-1170, 2009. (With Belén Iráizoz and Pedro Pascual.)

[Convergence in income inequality in the United States: A non parametric analysis](http://www.tandfonline.com/doi/abs/10.1080/13504850701439319?journalCode=rael20), Applied Economics Letters 16 (3), pp. 1365-1368, 2009. (With Pedro Pascual.)

[Spatial inequality in the European Union: Does regional efficiency matter?](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.508.4900&rep=rep1&type=pdf), Economics Bulletin 29 (4), pp. 2652-2659, 2009. (With Belén Iráizoz.)

[The spatial distribution of the Internet in the European Union: Does geographical proximity matter?](http://www.tandfonline.com/doi/abs/10.1080/09654310701748009), European Planning Studies 16 (1), pp. 119-142, 2008. (With Margarita Billón and Fernando Lera.)

[Spatial disparities in the European agriculture: A regional analysis](http://www.tandfonline.com/doi/abs/10.1080/00036840600905175), Applied Economics 40 (13), 1669-1684, 2008. (With Belén Iráizoz, Pedro Pascual and Manuel Rapún.)

[Fiscal decentralization and regional disparities: Evidence from several European Union countries](http://epn.sagepub.com/content/40/5/1185.abstract), Environment and Planning A 40 (5), pp. 1185-1201, 2008. (With Pedro Pascual.)

[Regional efficiency in the European Union](http://www.tandfonline.com/doi/abs/10.1080/09654310802315807), European Planning Studies 16 (8), pp. 1121-1143, 2008. (With Belén Iráizoz and Manuel Rapún.)

[Is there cross-country convergence in carbon dioxide emissions?](http://www.sciencedirect.com/science/article/pii/S0301421506001832), Energy Policy 35 (2), pp. 1363-1372, 2007.

[The spatial distribution of income inequality in the European Union](http://epn.sagepub.com/content/39/4/869.short), Environment and Planning A 39 (4), pp. 869-890, 2007. (With Pedro Pascual and Manuel Rapún.)

[Spatial inequality in productivity in the European Union: Sectoral and regional factors](http://irx.sagepub.com/content/30/4/384.short), International Regional Science Review 30 (4), pp. 384-407, 2007. (With Pedro Pascual and Manuel Rapún.)

[The Single Market and geographic concentration in the regions of the European Union](http://www.tandfonline.com/doi/abs/10.1080/13504850500461449), Applied Economics Letters 14 (6), pp. 463-466, 2007.

[Regional polarisation and national development in the European Union](http://usj.sagepub.com/content/44/1/99.abstract), Urban Studies 44 (1), pp. 99-122, 2007. (With Pedro Pascual).

[Spatial disparities in the European Union: An analysis of regional polarization](http://link.springer.com/article/10.1007%2Fs00168-006-0111-5), Annals of Regional Science 41 (2), pp. 401-429, 2007. (With Pedro Pascual and Manuel Rapún.)

[Distribution dynamics of energy intensities: A cross-country analysis](http://www.sciencedirect.com/science/article/pii/S0301421507001917), Energy Policy 35 (10), pp. 5254-5259, 2007.

[Spatial disparities in productivity in Central and Eastern Europe](http://www.jstor.org/stable/4380505), Eastern European Economics 45 (3), pp. 5-32, 2007. (With Pedro Pascual.)

[Is income inequality harmful for regional growth? Evidence from the European Union](http://usj.sagepub.com/content/44/10/1953.abstract), Urban Studies 44 (10),  pp. 1953-1971, 2007.

[The dynamics of regional disparities in Central and Eastern Europe during Transition](http://www.tandfonline.com/doi/abs/10.1080/09654310701550850?journalCode=ceps20), European Planning Studies 15 (10), pp. 1397-1421, 2007. (With Pedro Pascual and Manuel Rapún.)

[Regional dynamics and convergence profiles in the enlarged European Union: A non-parametric approach](http://onlinelibrary.wiley.com/doi/10.1111/j.1467-9663.2007.00426.x/abstract), Tijdschrift voor Economische en Sociale Geografie 98 (5), pp. 564-584, 2007. (With Manuel Rapún.)

[The world distribution of carbon dioxide emissions](http://www.tandfonline.com/doi/abs/10.1080/13504850500426285), Applied Economics Letters 14 (5), pp. 349-352, 2007.

[Regional polarization in the European Union](http://www.tandfonline.com/doi/pdf/10.1080/09654310500421089),  European Planning Studies 14 (4), pp. 459-484, 2006. (With Pedro Pascual and Manuel Rapún.)

[Mobility as movement: A measurement proposal based on transition matrices](http://www.accessecon.com/pubs/EB/2006/Volume4/EB-06D30001A.pdf), Economics Bulletin 4 (22), pp. 1-12, 2006. (With [Jorge Alcalde-Unzu](https://sites.google.com/site/alcaldeunzu/) and Pedro Pascual.)

[The dynamics of industrial concentration in the regions of the European Union](http://onlinelibrary.wiley.com/doi/10.1111/j.1468-2257.2006.00315.x/abstract), Growth and Change 37 (2), pp. 200-229, 2006. (With Pedro Pascual and Manuel Rapún.)

[The spatial distribution of welfare in the European Union](http://onlinelibrary.wiley.com/doi/10.1111/j.1467-9663.2006.00345.x/abstract), Tijdschrift voor Economische en Sociale Geografie 97 (4), pp. 331-342, 2006. (With Pedro Pascual and Manuel Rapún.)

[Regional specialization in the European Union](http://www.tandfonline.com/doi/abs/10.1080/00343400600868754), Regional Studies 40 (6), pp. 601-616, 2006. (With Pedro Pascual and Manuel Rapún.)

[Factor decomposition of spatial disparities: The case of the European regions](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.500.5003&rep=rep1&type=pdf), Economics Bulletin 18 (6), pp. 1-6, 2006. (With Pedro Pascual.)

[Regional mobility in the European Union](http://www.tandfonline.com/doi/abs/10.1080/00036840500427494), Applied Economics 38 (19), pp. 2237-2257, 2006. (With Pedro Pascual and Manuel Rapún.

[Regional disparities and national development revisited: The case of Western Europe](http://eur.sagepub.com/content/13/4/355.short), European Urban and Regional Studies 13 (4), pp. 355-369, 2006. (With Manuel Rapún.)

[Regional inequality in the European Union: Does industry mix matter?](http://www.tandfonline.com/doi/abs/10.1080/00343400500213473), Regional Studies 39 (6), pp. 679-697, 2005. (With Carlos Gil, Pedro Pascual and Manuel Rapún.)

[Cross-country disparities in welfare, 1970-1998](http://www.tandfonline.com/doi/abs/10.1080/1350485042000293112), Applied Economics Letters 12 (1), pp. 41-44, 2005. (With Pedro Pascual.)

[Inequality, polarisation and regional mobility in the European Union](http://usj.sagepub.com/content/42/7/1057.refs), Urban Studies 42 (7), pp. 1057-1076, 2005. (With Carlos Gil, Pedro Pascual and Manuel Rapún.)

[Regional welfare disparities: The case of the European Union](http://www.tandfonline.com/doi/abs/10.1080/00036840500142036), Applied Economics 37 (12), pp. 1423-1437, 2005. (With Carlos Gil and Pedro Pascual.)

[Regional bipolarization: The case of the European Union](http://onlinelibrary.wiley.com/doi/10.1111/j.1468-2427.2005.00633.x/abstract), International Journal of Urban and Regional Research 29 (4), pp. 984-995, 2005. (With Carlos Gil and Pedro Pascual.)

[Spatial disparities in productivity and industry mix: The case of the European regions](http://eur.sagepub.com/content/12/2/177.short), European Urban and Regional Studies 12 (2), pp. 177-194, 2005. (With [Juan Miguel Benito](http://www.econ.unavarra.es/~jbenito/index.html).)

[Is there convergence in income inequality levels among the European regions?](http://www.tandfonline.com/doi/abs/10.1080/13504850500245669), Applied Economics Letters 12 (12), pp. 763-767, 2005. (With Pedro Pascual.)

\
\

                       
